# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 534c5a8dd3bd6efed87ea15eb714ffc54c23a948a581d4309de139060af16e02a6c4d58762b2489f6e6d41c22c5d950ad1e4411de8fc8e223d08e684beb6b4e4

test:
  secret_key_base: c2c18cdf6ece2bae304fecd1a0a27925ac176c03d67d1cd76ab658a2518594f3e20b84cc582063c50f9bd04f1e3bf0e60d486b1b0076afad2dc56354d4f8c3d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
